default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-builtins"
          - "flake8-implicit-str-concat"
          - "flake8-no-pep420"

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.2
    # This hook filters sql files, so if there aren't sql files in the staging
    # area, then `pre-commit run` will skip it. Indeed, `pre-commit run
    # --all-files` will skip it too, as the `--all-files` argument doesn't work
    # as documented.
    hooks:
      - id: sqlfluff-fix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
