version: "3.0"

expectations:
  population_size: 1000

actions:
  query:
    run: >
      sqlrunner:latest
        --output output/rows.csv
        --log-file logs/log.json
        analysis/query.sql
    outputs:
      moderately_sensitive:
        rows: output/rows.csv
        log: logs/log.json

  data_dictionary_query:
    run: >
      sqlrunner:latest
        --output output/data_dictionary.csv
        --log-file logs/data_dictionary_log.json
        analysis/data_dictionary_query.sql
    outputs:
      moderately_sensitive:
        rows: output/data_dictionary.csv
        log: logs/data_dictionary_log.json

  decision_support_value_reference_query:
    run: >
      sqlrunner:latest
        --output output/decision_support_value_reference.csv
        --log-file logs/decision_support_value_reference_log.json
        analysis/decision_support_value_reference_query.sql
    outputs:
      moderately_sensitive:
        rows: output/decision_support_value_reference.csv
        log: logs/decision_support_value_reference_log.json

  vaccination_reference_query:
    run: >
      sqlrunner:latest
        --output output/vaccination_reference.csv
        --log-file logs/vaccination_reference_log.json
        analysis/vaccination_reference_query.sql
    outputs:
      moderately_sensitive:
        rows: output/vaccination_reference.csv
        log: logs/vaccination_reference_log.json

  make-html-reports:
    # --execute
    #   execute notebooks before converting them to HTML reports
    # --no-input
    #   exclude input cells and output prompts from HTML reports
    # --to=html
    #   convert notebooks to HTML reports (not e.g. to PDF reports)
    # --template basic
    #   use the basic (unstyled) template for HTML reports
    # --output-dir=output
    #   write HTML reports to the `output` directory
    run: >
      python:latest jupyter nbconvert
        --execute
        --no-input
        --to=html
        --template basic
        --output-dir=output
        analysis/*.ipynb
    needs:
      - query
      - vaccination_reference_query
    outputs:
      moderately_sensitive:
        reports: output/*.html

  categorical_columns:
    run: >
      sqlrunner:latest
        --output output/results_categorical_columns.csv
        --dummy-data-file analysis/dummy_results.csv
        analysis/query_tpp_categorical_columns.sql
    outputs:
      moderately_sensitive:
        results: output/results_categorical_columns.csv
