version: "3.0"

expectations:
  population_size: 1000

actions:
  query:
    run: >
      sqlrunner:latest
        --output output/rows.csv
        analysis/query.sql
    outputs:
      highly_sensitive:
        rows: output/rows.csv
